### ISSUE TITLE
Mage's Lucubration spell causes error

### ISSUE THREAD

**Issue by Yonman17** [Fair-Strides/Fvtt-PF1E-Spellbook-Generator#3]
For some reason the spell Mage's Lucubration doesn't show up in the spellbook when you drag it over from the repository. And when you try to create the spellbook it causes a massive error in the actor and you can't open the actor anymore.

**Comment by Fair-Strides** [comment]
Can you export the actor and upload it here?

And if you make a new actor for just this test, can you open the Console (F12) and add just that spell and see if there's errors? If so, then ya just need to screenshot the errors in the console for me.

**Comment by Yonman17** [comment]
[localhost-1680320368425.log](https://github.com/Fair-Strides/Fvtt-PF1E-Spellbook-Generator/files/11128387/localhost-1680320368425.log)
Here's a file of the error that happens when you load Mage's Lucubration
into the spellbook generator.  I'm pretty sure it's because that spell is
flawed and not from your program. The spell doesn't have a complete summary
and it's spell level is absent.

**Comment by Fair-Strides** [comment]
This should be fixed now?

**Comment by Yonman17** [comment]
It doesn't look like it's fixed. The spellbook generator will pop up but I
can't add any spells from the browser.
This isn't an error but I get this yellow warning.

commons.js:1703 Error: You are accessing the ActorCharacterPF#data object
which is no longer used. Since V10 the Document class and its contained
DataModel are merged into a combined data structure. You should now
reference keys which were previously contained within the data object
directly. at logCompatibilityWarning (commons.js:1692:19) at
ActorCharacterPF._logV10CompatibilityWarning (commons.js:6642:14) at get
data [as data] (commons.js:6542:24) at lookupProperty (
handlebars.min.js:27:16153) at Object.eval [as main] (eval at
createFunctionContext (handlebars.min.js:29:1808), <anonymous>:25:144) at c
(handlebars.min.js:27:15429) at d (handlebars.min.js:27:15744) at e (
handlebars.min.js:28:22748) at renderTemplate (foundry.js:6948:10) at async
SpellBookGenUI._renderInner (foundry.js:5271:16) at async
SpellBookGenUI._renderInner (foundry.js:5833:18) at async
SpellBookGenUI._render (foundry.js:5114:19) at async SpellBookGenUI._render
(foundry.js:5822:5)
logCompatibilityWarning @ commons.js:1703
_logV10CompatibilityWarning @ commons.js:6642
get data @ commons.js:6542
lookupProperty @ handlebars.min.js:27
eval @ VM90394:25
c @ handlebars.min.js:27
d @ handlebars.min.js:27
e @ handlebars.min.js:28
renderTemplate @ foundry.js:6948
await in renderTemplate (async)
_renderInner @ foundry.js:5271
_renderInner @ foundry.js:5833
_render @ foundry.js:5114
await in _render (async)
_render @ foundry.js:5822
render @ foundry.js:5067
_onDrop @ dialog.mjs:284
await in _onDrop (async)
callback @ foundry.js:56896
_handleDrop @ foundry.js:56947

**Comment by Yonman17** [comment]
nvm, it looks like it's working now
