### ISSUE TITLE
Won't launch on V11

### ISSUE THREAD

**Issue by sonofkyusss** [Fair-Strides/Fvtt-PF1E-Spellbook-Generator#5]
It's not working with V11, it won't launch :

Uncaught (in promise) TypeError: undefined. game.i18n.localize(...).format is not a function
[Detected 1 package: fair-strides-pf1e-spellbook-generator]
    at new SpellBookGenUI (dialog.mjs:28:99)
    at SpellBookGenUI.open (dialog.mjs:62:3)
    at showSpellBookGenUI (spellbook-gen.mjs:7:47)
    at Object.onclick (spellbook-gen.mjs:17:26)
    at HTMLAnchorElement.<anonymous> (foundry.js:5863:16)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168) #

**Comment by Fair-Strides** [comment]
That would make sense. I've not yet updated it to work with v11, but I will work on doing so.

**Comment by Fair-Strides** [comment]
Fixed with v2.1.1
